name = "DocUI"
license = "MIT"
description = "Hugo theme - modern documentation websites that are secure, fast, and SEO-ready — by default."
tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
min_version = "0.75.0"

[author]
  name = "Uttam Kr. Thapa"
  homepage = "https://www.ukthapa.com/"
